name: Pull Request

on:
  pull_request:
    branches: [main]
    paths-ignore:
      # - "**/version.h"
      - "doc/**"
      - "**.md"

env:
  LOCAL_REGISTRY: localhost:5000
  DOCKERFILE: docker/Dockerfile

jobs:
  ci:
    name: CI
    # needs: [get_runner_and_uid, build_docker_image]
    runs-on: [self-hosted, unicorn]
    env:
      CIBW_BUILD: "cp310-* cp311-* cp312-*"
      CIBW_SKIP: "pp* *-musllinux_*"
      CIBW_ARCHS: "x86_64"
      CIBW_MANYLINUX_X86_64_IMAGE: "manylinux_2_28"
    strategy:
      matrix:
        python-version:
          - "3.8"
          - "3.10"
          - "3.12"

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python (host)
        uses: actions/setup-python@v5
        with:
          check-latest: true
          python-version: ${{ matrix.python-version }}

      - name: Install Dependencies
        run: |
          python3 -m pip install -U pip
          python3 -m pip install build cibuildwheel pytest pylint pytest-cov typeguard

      - name: Build sdist (PEP 517)
        run: |
          rm -rf dist build *.egg-info wheelhouse
          python -m build --sdist

      - name: Build manylinux wheels with cibuildwheel
        run: |
          python -m cibuildwheel --platform linux --output-dir wheelhouse

      - name: Lint with Pylint
        run: |
          python3 -m pylint pyface \
          --rcfile=.github/workflows/.pylintrc
